version: "3.9"
services:
  telegraf:
    restart: always
    image: telegraf
    command: ["telegraf", "--config", "/etc/telegraf/telegraf.conf"]
    env_file: .env
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes: 
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
